name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  main:
    name: sdist + pure wheel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up latest Python
        uses: actions/setup-python@v4
        with:
          python-version: "*"

      - name: Install latest pip, build, twine
        run: |
          python -m pip install --upgrade --disable-pip-version-check pip
          python -m pip install --upgrade build twine

      - name: Build wheel and source distributions
        run: python -m build

      - name: Upload to PyPI via Twine
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload --verbose -u '__token__' dist/*